id: AE4EA6A4A
base_file: f5202.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:17:52.225743
  last_modified_at: 2022-06-17 12:17:52.225751
