id: AE4EA6A4A
base_file: fE4C8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:17:52.236820
  last_modified_at: 2022-06-17 12:17:52.236822
